version: '2.3'

services:

  train:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
    volumes:
      - ${WORKDIR}:/data
    command: >
      "python train.py"

  test:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
    volumes:
      - ${WORKDIR}:/data
    command: >
      "python test.py"
