version: '2.3'

services:

  test_c:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
      - TORCH_HOME=/storage/data/.torch
    volumes:
      - ${DATA_DIR:-/media/rsm/Data}:/storage/data
      - ${LOG_DIR:-/home/rsm/Data/logs}:/storage/logs
      - ${OUTPUT_DIR:-/home/rsm/Data/output}:/artifacts
    command: [
      'test.py',
      '--data_dir', '/storage/data/dataset',
      '--log_dir', '/storage/logs/c',
      '--output_dir', '/artifacts/c',
    ]

  test_e:
    extends: test_c
    command: [
      'test.py',
      '--data_dir', '/storage/data/dataset',
      '--log_dir', '/storage/logs/e',
      '--output_dir', '/artifacts/e',
    ]

  test_ea:
    extends: test_c
    command: [
       'test.py',
       '--data_dir', '/storage/data/dataset',
       '--log_dir', '/storage/logs/ea',
       '--output_dir', '/artifacts/ea',
    ]

  test_p:
    extends: test_c
    command: [
      'test.py',
      '--data_dir', '/storage/data/dataset',
      '--log_dir', '/storage/logs/p',
      '--output_dir', '/artifacts/p',
    ]

  test_pa:
    extends: test_c
    command: [
      'test.py',
      '--data_dir', '/storage/data/dataset',
      '--log_dir', '/storage/logs/pa',
      '--output_dir', '/artifacts/pa',
    ]

  train_c:
    extends: test_c
    command: [
      'train.py',
      '--accumulation_steps', '16',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/c',
      '--loss_configuration', '{"C": {"conv2_2": 2e-1, "conv5_4": 2e-2}}',
      '--output_dir', '/artifacts/c',
      '--weight_norm',
    ]

  train_e:
    extends: test_e
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/e',
      '--loss_configuration', '{"E": 1}',
      '--output_dir', '/artifacts/e',
      '--weight_norm',
    ]

  train_ea:
    extends: test_ea
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--discriminator_lr', '1e-3',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/ea',
      '--loss_configuration', '{"E": 1, "A": 1}',
      '--output_dir', '/artifacts/ea',
      '--weight_norm',
    ]

  train_p:
    extends: test_p
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/p',
      '--loss_configuration', '{"P": {"conv2_2": 2e-1, "conv5_4": 2e-2}}',
      '--output_dir', '/artifacts/p',
      '--weight_norm',
    ]

  train_pa:
    extends: test_pa
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--discriminator_lr', '1e-3',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/pa',
      '--loss_configuration', '{"P": {"conv2_2": 2e-1, "conv5_4": 2e-2}, "A": 1}',
      '--output_dir', '/artifacts/pa',
      '--weight_norm',
    ]

  test:
    extends: test_e

  train:
    extends: train_e
