version: '2.3'

services:

  test:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
      - TORCH_HOME=/storage/data/.torch
    volumes:
      - ${DATA_DIR:-/media/rsm/Data}:/storage/data
      - ${LOG_DIR:-/home/rsm/Data/logs}:/storage/logs
      - ${OUTPUT_DIR:-/home/rsm/Data/output}:/artifacts
    command: [
      'test.py',
      '--data_dir', '/storage/data/dataset',
      '--log_dir', '/storage/logs/mse',
      '--output_dir', '/artifacts/mse',
    ]

  train_mse:
    extends: test
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/mse',
      '--loss_configuration', '{"E": 1}',
      '--output_dir', '/artifacts/mse',
      '--weight_norm',
    ]

  train_perceptual:
    extends: test
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/perceptual',
      '--loss_configuration', '{"P": {"conv2_2": 2e-1, "conv5_4": 2e-2}}',
      '--output_dir', '/artifacts/perceptual',
      '--weight_norm',
    ]

  train_adversarial:
    extends: test
    command: [
      'train.py',
      '--data_dir', '/storage/data/dataset',
      '--input_size', '48', '48',
      '--learning_rate', '1e-3',
      '--log_dir', '/storage/logs/adversarial',
      '--loss_configuration', '{"E": 1, "A": 1e-3}',
      '--output_dir', '/artifacts/adversarial',
      '--weight_norm',
    ]

  train:
    extends: train_mse
