version: '2.3'

services:

  train:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
    volumes:
      - ${DATA_DIR:-/media/rsm/Data/dataset}:/storage/data
      - ${LOG_DIR:-/home/rsm/Data/logs}:/storage/logs
    command: [
      'train.py',
      '--data_dir', '/storage/data',
      '--input_size', '48', '48',
      '--log_dir', '/storage/logs',
      '--loss_configuration', '{"E": 1.0}']

  test:
    extends: train
    command: [
      'test.py',
      '--data_dir', '/storage/data',
      '--log_dir', '/storage/logs']
