version: '2.3'

services:

  train:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NV_GPU}
    volumes:
      - ${DATA_DIR:-/media/rsm/Data/dataset}:/storage/data
      - ${LOG_DIR:-/home/rsm/Data/logs}:/storage/logs
    command: >
      "train.py \
        --log_dir /storage/logs \
        --data_dir /storage/data"

  test:
    extends: train
    command: >
      "test.py \
        --log_dir /storage/logs \
        --data_dir /storage/data"
