name: sisr
channels: 
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - pillow
  - pytorch
  - torchvision
  - tensorboardx
  - pip:
    - git+git://github.com/Po-Hsun-Su/pytorch-ssim.git@master
